version: '3.8'

services:
  api:
    build:
      context: .
      target: production
    image: api_local-production
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URI: postgresql+psycopg2://bankar:bankar@db:5432/bankar
      PORT: 5000
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
    depends_on:
      - db
  manage:
    build:
      context: .
      target: manage
    image: api_local-manage
    environment:
      DATABASE_URI: postgresql+psycopg2://bankar:bankar@db:5432/bankar
      FLASK_ENV: production
      FLASK_DEBUG: 0
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_USER: bankar
      POSTGRES_PASSWORD: bankar
      POSTGRES_DB: bankar
    volumes:
      - ../data:/var/lib/postgresql/data

  test:
    build:
      context: .
      target: test
    image: api_local-test
    environment:
      TEST_DATABASE_URI: postgresql+psycopg2://bankar:bankar@db_test/test_bankar
    depends_on:
      - db_test
    stdin_open: true
    tty: true

  db_test:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: bankar
      POSTGRES_PASSWORD: bankar
      POSTGRES_DB: test_bankar
